### ISSUE TITLE
Resizing causes y=0 not to work anymore

### ISSUE THREAD

**Issue by IBwWG** [GimmickyApps/ScaleHuh#3]
Now with StageSizeScaleMode, the original problems go away somewhat, and we should theoretically be able to make use of the full screen, whatever its dimensions might be, via manual layout logic.

However, this is complicated by the fact that "y = 0" on the logo does not behave as one might expect.  As the logo changes size, "y = 0" somehow seems to centre the logo vertically at y = 50, which only looks correct in the third screenshot when the logo is 100px tall.  Otherwise, as you can see in the other screenshots, either the logo has extra whitespace above it, or it starts offscreen with a visually negative y value.

![scalemode-y-problem-1](https://cloud.githubusercontent.com/assets/16719964/12449212/0117aa74-bf7c-11e5-935c-c1c6a241c634.png)
![scalemode-y-problem-2](https://cloud.githubusercontent.com/assets/16719964/12449213/0136ba36-bf7c-11e5-9b48-302bf4b76fda.png)
![scalemode-y-problem-3](https://cloud.githubusercontent.com/assets/16719964/12449214/013d44fa-bf7c-11e5-837a-7bed34439e08.png)
![scalemode-y-problem-4](https://cloud.githubusercontent.com/assets/16719964/12449215/013ed414-bf7c-11e5-88e2-39a5e16f0737.png)

**Comment by player-03** [comment]
This is an issue with FlxSprite. You need to call updateHitbox() after setGraphicSize(), or else the offset variable will be wrong.

**Comment by IBwWG** [comment]
@player-03 thank you so much.  That solves it!  I had considered updateHitbox() but had not actually tried it out, because I had thought that, being this was a menu screen and I wasn't using any physics, hitboxes did not apply to the problem.
